#!/usr/bin/env python3
"""Lunes Host login automation using SeleniumBase UC mode."""

import json
import os
import sys
import time
from pathlib import Path

from seleniumbase import SB


SERVER_ID = os.getenv("SERVER_ID", "")
EMAIL = os.getenv("LOGIN_EMAIL", "")
PASSWORD = os.getenv("LOGIN_PASSWORD", "")
PROXY_SERVER = os.getenv("PROXY_SERVER", "")

LOGIN_URL = "https://betadash.lunes.host/login"
TARGET_URL = (
    f"https://betadash.lunes.host/servers/{SERVER_ID}"
    if SERVER_ID
    else LOGIN_URL
)

ARTIFACTS_DIR = Path(__file__).resolve().parent.parent / "artifacts"
SCREENSHOT_PATH = ARTIFACTS_DIR / "screenshots" / "login-result.png"
RESULT_PATH = ARTIFACTS_DIR / "login-result.json"

NAVIGATION_ATTEMPTS = 3
NAVIGATION_RETRY_SECONDS = 10
TURNSTILE_ATTEMPTS = 3


def save_result(sb, success, error=None):
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    SCREENSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)

    url = ""
    if sb is not None:
        try:
            url = sb.get_current_url()
        except Exception:
            pass
        try:
            sb.save_screenshot(str(SCREENSHOT_PATH))
        except Exception as exc:
            print(f"[Screenshot] Failed: {exc}")

    result = {
        "success": success,
        "url": url,
        "server_id": SERVER_ID,
        "error": error,
    }
    RESULT_PATH.write_text(json.dumps(result), encoding="utf-8")
    print(f"[Result] {result}")


def has_upstream_error(sb):
    try:
        title = (sb.get_title() or "").lower()
        source = (sb.get_page_source() or "")[:10000].lower()
    except Exception:
        return False

    markers = (
        "bad gateway",
        "host error",
        "internal server error",
        "error code 502",
        "error code 503",
        "error code 504",
    )
    return any(marker in title or marker in source for marker in markers)


def navigate_with_retry(sb, url):
    last_error = "navigation_failed"
    for attempt in range(1, NAVIGATION_ATTEMPTS + 1):
        try:
            if getattr(sb, "_lunes_cdp_active", False):
                sb.cdp.open(url)
            else:
                sb.activate_cdp_mode(url)
                sb._lunes_cdp_active = True
            sb.sleep(4)
            if not has_upstream_error(sb):
                return True, None
            last_error = "upstream_server_error"
            print(
                f"[Navigation] Target returned a server error "
                f"(attempt {attempt}/{NAVIGATION_ATTEMPTS})"
            )
        except Exception as exc:
            last_error = f"navigation_exception:{type(exc).__name__}"
            print(
                f"[Navigation] {last_error} "
                f"(attempt {attempt}/{NAVIGATION_ATTEMPTS}): {exc}"
            )

        if attempt < NAVIGATION_ATTEMPTS:
            time.sleep(NAVIGATION_RETRY_SECONDS * attempt)

    return False, last_error


def get_turnstile_token(sb):
    try:
        return sb.execute_script(
            """
            const names = ['cf-turnstile-response', 'g-recaptcha-response'];
            for (const name of names) {
              const element = document.querySelector(`[name="${name}"]`);
              if (element && element.value) return element.value;
            }
            return '';
            """
        ) or ""
    except Exception:
        return ""


def wait_for_turnstile(sb, timeout=15):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if get_turnstile_token(sb):
            return True
        time.sleep(1)
    return False


def solve_turnstile(sb):
    if wait_for_turnstile(sb, timeout=3):
        print("[Turnstile] Token was generated automatically")
        return True

    for attempt in range(1, TURNSTILE_ATTEMPTS + 1):
        print(f"[Turnstile] Solve attempt {attempt}/{TURNSTILE_ATTEMPTS}")
        try:
            sb.solve_captcha()
        except Exception as exc:
            print(f"[Turnstile] CDP solver failed: {exc}")
        if wait_for_turnstile(sb, timeout=12):
            print("[Turnstile] Token generated")
            return True

        try:
            sb.uc_gui_click_captcha(blind=True)
        except Exception as exc:
            print(f"[Turnstile] GUI fallback failed: {exc}")
        if wait_for_turnstile(sb, timeout=8):
            print("[Turnstile] Token generated by GUI fallback")
            return True

    print("[Turnstile] Token not visible; continuing with form submission")
    return False


def fill_login_form(sb):
    email_selector = "input#email, input[name='email'], input[type='email']"
    password_selector = "input#password, input[name='password'], input[type='password']"

    sb.wait_for_element_visible(email_selector, timeout=20)
    sb.wait_for_element_visible(password_selector, timeout=20)
    sb.type(email_selector, EMAIL)
    sb.type(password_selector, PASSWORD)
    sb.sleep(1)


def login(sb):
    navigation_ok, navigation_error = navigate_with_retry(sb, TARGET_URL)
    if not navigation_ok:
        return False, navigation_error

    current_url = sb.get_current_url()
    if "/login" not in current_url and (
        not SERVER_ID or f"/servers/{SERVER_ID}" in current_url
    ):
        print("[Login] Existing session is valid")
        return True, None

    print("[Login] Filling credentials before Turnstile")
    try:
        fill_login_form(sb)
    except Exception as exc:
        return False, f"login_form_missing:{type(exc).__name__}"

    turnstile_solved = solve_turnstile(sb)

    print("[Login] Submitting form")
    try:
        sb.click("button[type='submit']", timeout=10)
    except Exception as exc:
        return False, f"submit_failed:{type(exc).__name__}"

    sb.sleep(10)
    if has_upstream_error(sb):
        return False, "upstream_server_error"

    current_url = sb.get_current_url()
    if "/login" in current_url:
        error = "login_rejected"
        if not turnstile_solved and not get_turnstile_token(sb):
            error = "turnstile_token_missing"
        return False, error

    if SERVER_ID and f"/servers/{SERVER_ID}" not in current_url:
        navigation_ok, navigation_error = navigate_with_retry(sb, TARGET_URL)
        if not navigation_ok:
            return False, navigation_error
        current_url = sb.get_current_url()

    if SERVER_ID and f"/servers/{SERVER_ID}" not in current_url:
        return False, "server_page_not_reached"

    if has_upstream_error(sb):
        return False, "upstream_server_error"

    return True, None


def main():
    if not EMAIL or not PASSWORD:
        save_result(None, False, "credentials_missing")
        return 1

    options = {
        "uc": True,
        "test": True,
        "incognito": True,
        "locale": "en",
        "xvfb": True,
        "xvfb_metrics": "1366,900",
    }
    if PROXY_SERVER:
        options["proxy"] = PROXY_SERVER
        print(f"[Browser] Proxy enabled: {PROXY_SERVER}")

    try:
        with SB(**options) as sb:
            success, error = login(sb)
            save_result(sb, success, error)
            return 0 if success else 1
    except Exception as exc:
        error = f"browser_exception:{type(exc).__name__}"
        print(f"[Browser] {error}: {exc}")
        save_result(None, False, error)
        return 1


if __name__ == "__main__":
    sys.exit(main())
